### ISSUE TITLE
Updating resolution notes does not change resolution note in presentation

### ISSUE THREAD

**Issue by dstockhammer** [grafana/incident-community#47] opened 2023-01-13 14:35 UTC
**Describe the bug**
When updating an incident's resolution notes, the presentation view still only ever shows the original resolution note.

**To Reproduce**
1. Create an incident
2. Close with resolution note `aaaa`
3. Edit resolution note to `bbbb`
4. Go to presentation, the note is still `aaaa`

**Expected behavior**
Resolution note changes should be respected by the presentation view.

**Relevant system information**
- [Cloud Pro (Licensed)](https://grafana.com/products/enterprise/?utm_source=grafana_footer) [v9.3.2-67a213dc85 (67a213dc85)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Incidents v1.0.26

**Comment by matryer** [comment] 2023-01-16 12:25
I genuinely don't even know how this is possible - definitely a bug, thanks @dstockhammer.

**Comment by fcjack** [comment] 2023-01-16 16:17
Hi @dstockhammer, thanks for opening this issue.
It is fixed and we should have a release soon that will resolve this issue

**Comment by paulcoghlan** [comment] 2023-02-02 11:33
Hi again @dstockhammer.  We released a new version (1.0.29) yesterday, would you mind taking another look at presentation mode, we believe this issue should be resolved now?

Thanks again for your patience.

**Comment by dstockhammer** [comment] 2023-02-02 13:48
Hi there, I can still repro the issue on v1.0.29 in Grafana Cloud

**Comment by paulcoghlan** [comment] 2023-02-03 13:30
> Hi there, I can still repro the issue on v1.0.29 in Grafana Cloud

@dstockhammer - very sorry about that, this was fixed but it seems there has been a regression due to some other changes. We'll keep you informed on progress.

**Comment by paulcoghlan** [comment] 2023-02-23 09:34
@dstockhammer - apologies again for the mix-up, but we've made another release and presentation mode resolution notes should be fixed now.

I've tested manually but maybe you could take another look?

Thanks again for your patience.

**Comment by idk-92** [comment] 2023-02-28 05:02
Closing this issue as this has been resolved, please let us know if is still a problem and we'll reopen this issue

**Closed by idk-92** 2023-02-28 05:02 UTC
Labels: bug, kata:incident_ga
