### ISSUE TITLE
JIRA IRM Integration not updating Issue state

### ISSUE THREAD

**Issue by benediktwetzel** [grafana/incident-community#64] opened 2023-05-16 11:01 UTC
**Describe the bug**
The Grafana IRM integration for Jira is not working as expected. Grafana is able to create a new issue for a new incident. But when I resolve the incident, Grafana displays an error and does not update the status of the incident in Jira accordingly.

I understand the error message (see below) that there is no transition to the desired status in Jira, but there is.

![image](https://github.com/grafana/incident-community/assets/45208625/e595b47c-ae76-4c7f-ae2d-a3074e7d0ae4)

We are using Jira Software Cloud.

**To Reproduce**
1. Go to IRM and install the Jira integration
2. Click "Run when an event fires"  and add a new action:
 
![image](https://github.com/grafana/incident-community/assets/45208625/5f28ef16-a693-418b-986c-4498aeab3520)
4. Create a new Incident via the Grafana IRM UI (Grafana successfully creates a new Issue in JIRA).
5. Resolve the Incident in Grafana
6. The error message is displayed (see above) and the status of the Jira output does not change.

**Expected behavior**
We expect, that the state of the Jira issue changed as configured.

**Relevant system information**
Grafana Cloud, Jira Software Cloud

Do you have an idea, how to solve this problem?

Thanks!

**Comment by paulcoghlan** [comment] 2023-05-22 12:37
@benediktwetzel - apologies again. I've tried reproducing the fault but I've not been able to. Just wanted to check:

- Have you created any incident since you saw this problem? Do you still get the same problem?
- Have you tried removing and added the event hook (Under "Create a Jira Issue" click on the "Trash" icon in the top-right)?

Kind regards, Paul

**Comment by benediktwetzel** [comment] 2023-05-23 08:52
Hello @paulcoghlan,
thank you for your reply.

1. yes, we create additional incidents, but when I click on "solve", I get the error message mentioned above.
2. yes, I have tried several times. I have also tried different projects in JIRA and different transitions.

Do you mean the JIRA workflow instead of Github? But no, we haven't changed any workflow :/ 

Do you have another idea or can I give you more information?

Thanks a lot for that! 
Best, 
benedict

**Comment by paulcoghlan** [comment] 2023-05-23 11:46
> Do you mean the JIRA workflow instead of Github? But no, we haven't changed any workflow :/

Hi @benediktwetzel yes I was wondering if you had made any changes to the JIRA workflow...

I think the next step is to take a look at your instance (with your permission) so maybe we could follow up in a private support issue?

Best regards, Paul

**Comment by benediktwetzel** [comment] 2023-05-23 14:24
Hi @paulcoghlan,

I have also opened a support ticket. Are you able to find this ticket? If so, I would be happy if you could reply me in this ticket. 

Thank you very much for that!
Best regards,
Benedikt

**Comment by matryer** [comment] 2023-06-01 11:09
Hey @benediktwetzel - I'm having a look at this today.

Can you let me know what you chose for the **Select issue type** dropdown, when you set this up?

**Comment by matryer** [comment] 2023-06-01 16:26
@benediktwetzel I'm afraid we cannot reproduce. 

It is trying to transition the `Fix` issue, but the transition ID (which it gets from the form when you set up the hook) isn't found. We don't know how this can happen, and may be something unique to Jira.

I wonder, can you try a different type of thing (i.e. not `Fix` but something else) to see if you get the same problem?

**Comment by benediktwetzel** [comment] 2023-06-06 14:42
Hi @matryer 

thank you. I have tried but it does not work. I have answered more details on the support ticket. 

Best,
Benedikt

**Comment by matryer** [comment] 2023-06-12 08:58
OK - closing here and we'll continue that thread. Thank you.

**Closed by matryer** 2023-06-12 08:58 UTC
